apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-hzap
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-swys-tenant/status-quarkus-io/statusquarkusio-hzap@sha256:013b254f32627a8df913736a4b007f0fb199dd0dc3ec22ee7979915b2cac00dd
        name: my-java-quarkus
        resources: {}
status: {}
